### ISSUE TITLE
project name made incorrectly for miseq runs

### ISSUE THREAD

**Issue by aledj2** [moka-guys/dnanexus_upload_multiqc#10]
If miseq the flowcell id contains a "-"
The multiqc file name is split on "-" to capture the project id but the presense of this extra dash means this is now incorrect
consider adding a test for sequencer or splitting the name in a different way

**Comment by aledj2** [comment]
https://github.com/moka-guys/dnanexus_upload_multiqc/blob/97c754db672da2139c2fd2e0a52308bb58f85876/src/code.sh#L51

change needs to happen here, I think cut takes a single delimiter but if can use something else eg regex to remove -multiqc.html

**Comment by RachelDuffin** [comment]
Can it be changed to `cut -d"-multiqc.html" -f1` if it is always removing the same file ending?

**Comment by aledj2** [comment]
try it out! I think cut -d only takes a single character as the delimiter.

**Comment by RachelDuffin** [comment]
Tested and the following code works for both cases with a single "-" or two "-". It takes the html name, reverses it, cuts at "-" and takes the second and third elements after cutting, then reverses these again to give the correct file name (this makes sure that it is always the "-multiqc.html" element being removed regardless of the number of "-" present.

`echo $multiqc_html_name  | rev | cut -f2-3 -d "-" | rev`

**Comment by aledj2** [comment]
cool! has it been tested for both nextseq and miseq project names?

**Comment by RachelDuffin** [comment]
Yeah I have tested it for both and it works
